"""Add composite unique constraint to rooms

Revision ID: 0a452c6ddd1e
Revises: ccba4948400a
Create Date: 2024-09-29 04:03:05.305324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a452c6ddd1e'
down_revision: Union[str, None] = 'ccba4948400a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rooms_room_number', table_name='rooms')
    op.create_index(op.f('ix_rooms_room_number'), 'rooms', ['room_number'], unique=False)
    op.create_unique_constraint('_community_room_uc', 'rooms', ['community_id', 'room_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_community_room_uc', 'rooms', type_='unique')
    op.drop_index(op.f('ix_rooms_room_number'), table_name='rooms')
    op.create_index('ix_rooms_room_number', 'rooms', ['room_number'], unique=True)
    # ### end Alembic commands ###
