"""Made fields optional in Task model

Revision ID: 550aefcd9d2f
Revises: 401e2621eec0
Create Date: 2024-09-25 13:46:45.947870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '550aefcd9d2f'
down_revision: Union[str, None] = '401e2621eec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', name='task_status'),
               nullable=False)
    op.alter_column('tasks', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', name='task_status'),
               nullable=True)
    # ### end Alembic commands ###
