"""Add community_id to AlexaDevice

Revision ID: 5cacc5422961
Revises: 0a452c6ddd1e
Create Date: 2024-10-01 13:55:38.209981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cacc5422961'
down_revision: Union[str, None] = '0a452c6ddd1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alexa_devices', sa.Column('community_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alexa_devices', 'communities', ['community_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alexa_devices', type_='foreignkey')
    op.drop_column('alexa_devices', 'community_id')
    # ### end Alembic commands ###
