"""Add room_id to Task model

Revision ID: 692194ba1dea
Revises: 7d5789b5f9f0
Create Date: 2024-10-03 17:14:40.767536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692194ba1dea'
down_revision: Union[str, None] = '7d5789b5f9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'room_id')
    # ### end Alembic commands ###
