"""Revert to original enum for role with manager added

Revision ID: 852ad2ca9dfb
Revises: 74d07462563f
Create Date: 2024-09-27 12:14:02.891495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852ad2ca9dfb'
down_revision: Union[str, None] = '74d07462563f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
