"""Add manager role to user_role enum

Revision ID: 92440f11db46
Revises: 852ad2ca9dfb
Create Date: 2024-09-27 12:46:49.727984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92440f11db46'
down_revision: Union[str, None] = '852ad2ca9dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE user_role ADD VALUE 'manager';")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
