"""Add created_at field to Community model

Revision ID: b109416ee2c3
Revises: 7e6183cd8429
Create Date: 2024-09-25 17:42:57.116203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b109416ee2c3'
down_revision: Union[str, None] = '7e6183cd8429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_communities_created_at'), 'communities', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communities_created_at'), table_name='communities')
    op.drop_column('communities', 'created_at')
    # ### end Alembic commands ###
