"""Added created_by field to Community model

Revision ID: cee7280e5b74
Revises: b109416ee2c3
Create Date: 2024-09-26 16:20:51.656117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee7280e5b74'
down_revision: Union[str, None] = 'b109416ee2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('created_by_id', sa.Integer(), nullable=True))
    
    # Set a default value for existing rows before making the column non-nullable
    op.execute("UPDATE communities SET created_by_id = 1")  # Replace 1 with a valid user ID

    # Make the column non-nullable
    op.alter_column('communities', 'created_by_id', nullable=False)
    
    op.create_foreign_key(None, 'communities', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_column('communities', 'created_by_id')
    # ### end Alembic commands ###
